name: dio_benchmark
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3
  benchmark_harness: ^2.0.0
  barbecue:
  intl:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
